services:
  zookeeper:
    image: debezium/zookeeper:1.6

  kafka:
    image: debezium/kafka:1.6
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  debezium-connector:
    build:
      context: .
      args:
        METRICS_PORT: 8080
    ports:
      - '8080:8080'
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
